name: Build and test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        sanitize: [OFF, ON]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTF_ED448_SANITIZE=${{ matrix.sanitize }}
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
